In [4]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import os
print(os.listdir("./Subject3/Subject3_Figures_50rps/"))
from keras.models import Sequential


['test', 'train', 'validation']


In [5]:
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense
from keras.layers import Dropout
from keras.optimizers import SGD

In [25]:
classifier = Sequential()

# Step 1 - Convolution
classifier.add(Conv2D(32, (3, 3), input_shape = (144, 144, 3), activation = 'relu'))


# Step 2 - Pooling
classifier.add(MaxPooling2D(pool_size = (2, 2)))

# Adding a second convolutional layer
classifier.add(Conv2D(32, (3, 3), activation = 'relu'))
classifier.add(MaxPooling2D(pool_size = (2, 2)))



# Step 3 - Flattening
classifier.add(Flatten())

# Step 4 - Full connection
classifier.add(Dense(units = 144+144, activation = 'relu'))
classifier.add(Dropout(rate=0.5))
classifier.add(Dense(units = 8, activation = 'sigmoid'))

# # Compiling the CNN

classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['categorical_accuracy'])

In [8]:
from keras.preprocessing.image import ImageDataGenerator

In [68]:
train_set = ImageDataGenerator().flow_from_directory('./Subject3/Subject3_Figures_50rps/train/',
                                                 target_size = (224, 224),
                                                 batch_size =32,
                                                 class_mode = 'categorical',
                                                 subset='training')
test_set = ImageDataGenerator().flow_from_directory('./Subject3/Subject3_Figures_50rps/test/',
                                                 target_size = (224, 224),
                                                 batch_size =32,
                                                 class_mode = 'categorical',
                                                 shuffle=False
                                                 )
validation_set = ImageDataGenerator().flow_from_directory('./Subject3/Subject3_Figures_50rps/validation/',
                                                 target_size = (224, 224),
                                                 batch_size =32,
                                                 class_mode = 'categorical',
                                                 )

Found 640 images belonging to 8 classes.
Found 160 images belonging to 8 classes.
Found 160 images belonging to 8 classes.


In [14]:
import keras
vgg16_model = keras.applications.vgg16.VGG16()

Instructions for updating:
Colocations handled automatically by placer.


In [15]:
vgg16_model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
__________

In [16]:
model = Sequential()
i = 0
for layer in vgg16_model.layers:
    i +=1
    if i < 23 :
        model.add(layer)

In [17]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
_________________________________________________________________
block3_conv1 (Conv2D)        (None, 56, 56, 256)       295168    
__________

In [18]:
for layer in model.layers:
    layer.trainable=False

In [19]:
model.add(Dense(8,activation = 'softmax'))

In [20]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
_________________________________________________________________
block3_conv1 (Conv2D)        (None, 56, 56, 256)       295168    
__________

In [21]:
from keras.optimizers import Adam
model.compile(Adam(lr=0.0001), loss='categorical_crossentropy', metrics=['accuracy'])

In [23]:
model.fit_generator(train_set,steps_per_epoch=20,validation_data=validation_set, validation_steps=5,epochs=30)

Epoch 1/30
20/20 [==============================] - 206s 10s/step - loss: 1.1101 - acc: 0.6156 - val_loss: 1.2804 - val_acc: 0.5125
Epoch 2/30
20/20 [==============================] - 205s 10s/step - loss: 1.0446 - acc: 0.6469 - val_loss: 1.2116 - val_acc: 0.5125
Epoch 3/30
20/20 [==============================] - 206s 10s/step - loss: 0.9799 - acc: 0.6953 - val_loss: 1.1838 - val_acc: 0.5375
Epoch 4/30
20/20 [==============================] - 206s 10s/step - loss: 0.8998 - acc: 0.7047 - val_loss: 1.2480 - val_acc: 0.4875
Epoch 5/30
20/20 [==============================] - 207s 10s/step - loss: 0.8915 - acc: 0.7047 - val_loss: 1.1668 - val_acc: 0.5250
Epoch 6/30
20/20 [==============================] - 206s 10s/step - loss: 0.8138 - acc: 0.7234 - val_loss: 1.0972 - val_acc: 0.5875
Epoch 7/30
20/20 [==============================] - 206s 10s/step - loss: 0.7924 - acc: 0.7594 - val_loss: 1.1888 - val_acc: 0.4688
Epoch 8/30
20/20 [==============================] - 206s 10s/step - loss: 0.

In [3]:
len(train_set)

NameError: name 'train_set' is not defined

In [28]:
model_json = model.to_json()
with open("final_model.json", "w") as json_file:
    json_file.write(model_json)

# serialize weights to HDF5
model.save_weights("final_model_weights.h5")
print("Saved model to disk")

Saved model to disk


In [26]:
model.save("ECG_CNN_MODEL.h5")

In [27]:
loaded_model = keras.models.load_model("ECG_CNN_MODEL.h5")

ValueError: You are trying to load a weight file containing 16 layers into a model with 0 layers

In [ ]:
from keras.models import model_from_json
# load json and create model
json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("model.h5")
print("Loaded model from disk")

In [69]:
y_pred=model.predict_generator(test_set, steps=5, verbose=1)

5/5 [==============================] - 41s 8s/step


In [70]:
y_pred[0]

array([6.9950736e-01, 4.9035285e-02, 1.7334458e-03, 3.5223335e-03,
       6.0629175e-04, 3.2598902e-02, 4.2284131e-03, 2.0876805e-01],
      dtype=float32)

In [85]:
y_pred_classes = y_pred.argmax(axis=-1) 

In [87]:
y_true = test_set.classes
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(test_set.classes, y_pred_classes))
print(classification_report(test_set.classes, y_pred_classes))

[[15  1  1  0  0  1  1  1]
 [ 8 12  0  0  0  0  0  0]
 [ 0  0 19  0  0  1  0  0]
 [ 0  0  0 20  0  0  0  0]
 [ 0  0  0 12  8  0  0  0]
 [ 0  0  0  9  0  9  0  2]
 [ 1  0  1  1  0  0 17  0]
 [ 0  0  0  5  0 10  0  5]]
              precision    recall  f1-score   support

           0       0.62      0.75      0.68        20
           1       0.92      0.60      0.73        20
           2       0.90      0.95      0.93        20
           3       0.43      1.00      0.60        20
           4       1.00      0.40      0.57        20
           5       0.43      0.45      0.44        20
           6       0.94      0.85      0.89        20
           7       0.62      0.25      0.36        20

   micro avg       0.66      0.66      0.66       160
   macro avg       0.73      0.66      0.65       160
weighted avg       0.73      0.66      0.65       160



In [73]:
scores = model.evaluate_generator(test_set, steps=5,verbose=1)


5/5 [==============================] - 42s 8s/step


In [75]:
scores

[0.9010190546512604, 0.65625]

In [45]:
labels = []   # store all the generated label batches
max_iter = 160  # maximum number of iterations, in each iteration one batch is generated; the proper value depends on batch size and size of whole data
i = 0
for d, l in test_set:
    labels.append(l)
    i += 1
    if i == max_iter:
        break

In [76]:
y_true=np.argmax(labels, axis=-1).reshape(-1,1)

In [77]:
y_true[:5]

array([[3],
       [6],
       [4],
       [1],
       [3]], dtype=int64)

In [55]:
y_true[5:8]

array([[4],
       [5],
       [6]], dtype=int64)